[client]
showErrorDetails = true
logger.level = "info"

[server]
port = 8501
headless = true
runOnSave = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0D47A1"
backgroundColor = "#2e2e2eff"
secondaryBackgroundColor = "#000000ff"
textColor = "#ffffffff"
font = "sans serif"
