[client]
showErrorDetails = true
logger.level = "info"

[server]
port = 8501
headless = true
runOnSave = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0D47A1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
